server:
  port: 8090
  ip: localhost
#Logging
logging:
  level:
    root: info
  file:
    name: logs/security/security.log

spring:
  application:
    name: security-service
  datasource:
    url: jdbc:postgresql://${server.ip}:5432/postgres?currentSchema=auth
    username: postgres
    password: postgrespw
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  properties:
    hibernate:
      default_schema: auth
  flyway:
    url: jdbc:postgresql://${server.ip}:5432/postgres
    user: postgres
    password: postgrespw
    default-schema: auth
#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          issuer-uri: http://${server.ip}:28080/realms/i113_realm
  instance:
    status-page-url-path: api/auth/actuator/info
    health-check-url-path: api/auth/actuator/health
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      default-zone: http://${server.ip}:8761/eureka

jwt:
  header: Authorization
  secret: proselyte
  #expiration: 18000 #5h 300m
  expiration: 900 #15m

